# Generated by Django 3.1.2 on 2021-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='work2',
            field=models.CharField(default='', max_length=100, verbose_name='Project 2 URL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='work1',
            field=models.CharField(default='', max_length=100, verbose_name='Project 1 URL'),
        ),
    ]
