# Generated by Django 3.1.2 on 2021-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210610_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='skill1p',
            field=models.IntegerField(default=1, verbose_name='Skill 1 percentage'),
        ),
    ]
