# Generated by Django 3.1.2 on 2021-06-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210610_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='project1',
            field=models.CharField(default='', max_length=100, verbose_name='Project 1 name'),
        ),
        migrations.AddField(
            model_name='member',
            name='project2',
            field=models.CharField(default='', max_length=100, verbose_name='Project 2 name'),
        ),
        migrations.AddField(
            model_name='member',
            name='project3',
            field=models.CharField(default='', max_length=100, verbose_name='Project 3 name'),
        ),
        migrations.AddField(
            model_name='member',
            name='project4',
            field=models.CharField(default='', max_length=100, verbose_name='Project 4 name'),
        ),
        migrations.AddField(
            model_name='member',
            name='project5',
            field=models.CharField(default='', max_length=100, verbose_name='Project 5 name'),
        ),
        migrations.AddField(
            model_name='member',
            name='project6',
            field=models.CharField(default='', max_length=100, verbose_name='Project 6 name'),
        ),
    ]
