# Generated by Django 3.1.2 on 2021-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210610_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
    ]
