# Generated by Django 3.1.2 on 2021-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_member_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='resume',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='images/perfil.png', null=True, upload_to='images'),
        ),
    ]
